// Code generated by entc, DO NOT EDIT.

package expert

const (
	// Label holds the string label denoting the expert type in the database.
	Label = "expert"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldExpertName holds the string denoting the expert_name field in the database.
	FieldExpertName = "expert_name"

	// EdgeDentists holds the string denoting the dentists edge name in mutations.
	EdgeDentists = "dentists"

	// Table holds the table name of the expert in the database.
	Table = "experts"
	// DentistsTable is the table the holds the dentists relation/edge.
	DentistsTable = "dentists"
	// DentistsInverseTable is the table name for the Dentist entity.
	// It exists in this package in order to avoid circular dependency with the "dentist" package.
	DentistsInverseTable = "dentists"
	// DentistsColumn is the table column denoting the dentists relation/edge.
	DentistsColumn = "expert_id"
)

// Columns holds all SQL columns for expert fields.
var Columns = []string{
	FieldID,
	FieldExpertName,
}

var (
	// ExpertNameValidator is a validator for the "expert_name" field. It is called by the builders before save.
	ExpertNameValidator func(string) error
)
