// Code generated by entc, DO NOT EDIT.

package expert

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/tanapon395/playlist-video/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Expert {
	return predicate.Expert(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Expert {
	return predicate.Expert(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Expert {
	return predicate.Expert(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Expert {
	return predicate.Expert(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Expert {
	return predicate.Expert(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Expert {
	return predicate.Expert(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Expert {
	return predicate.Expert(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Expert {
	return predicate.Expert(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Expert {
	return predicate.Expert(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// ExpertName applies equality check predicate on the "expert_name" field. It's identical to ExpertNameEQ.
func ExpertName(v string) predicate.Expert {
	return predicate.Expert(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldExpertName), v))
	})
}

// ExpertNameEQ applies the EQ predicate on the "expert_name" field.
func ExpertNameEQ(v string) predicate.Expert {
	return predicate.Expert(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldExpertName), v))
	})
}

// ExpertNameNEQ applies the NEQ predicate on the "expert_name" field.
func ExpertNameNEQ(v string) predicate.Expert {
	return predicate.Expert(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldExpertName), v))
	})
}

// ExpertNameIn applies the In predicate on the "expert_name" field.
func ExpertNameIn(vs ...string) predicate.Expert {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Expert(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldExpertName), v...))
	})
}

// ExpertNameNotIn applies the NotIn predicate on the "expert_name" field.
func ExpertNameNotIn(vs ...string) predicate.Expert {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Expert(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldExpertName), v...))
	})
}

// ExpertNameGT applies the GT predicate on the "expert_name" field.
func ExpertNameGT(v string) predicate.Expert {
	return predicate.Expert(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldExpertName), v))
	})
}

// ExpertNameGTE applies the GTE predicate on the "expert_name" field.
func ExpertNameGTE(v string) predicate.Expert {
	return predicate.Expert(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldExpertName), v))
	})
}

// ExpertNameLT applies the LT predicate on the "expert_name" field.
func ExpertNameLT(v string) predicate.Expert {
	return predicate.Expert(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldExpertName), v))
	})
}

// ExpertNameLTE applies the LTE predicate on the "expert_name" field.
func ExpertNameLTE(v string) predicate.Expert {
	return predicate.Expert(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldExpertName), v))
	})
}

// ExpertNameContains applies the Contains predicate on the "expert_name" field.
func ExpertNameContains(v string) predicate.Expert {
	return predicate.Expert(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldExpertName), v))
	})
}

// ExpertNameHasPrefix applies the HasPrefix predicate on the "expert_name" field.
func ExpertNameHasPrefix(v string) predicate.Expert {
	return predicate.Expert(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldExpertName), v))
	})
}

// ExpertNameHasSuffix applies the HasSuffix predicate on the "expert_name" field.
func ExpertNameHasSuffix(v string) predicate.Expert {
	return predicate.Expert(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldExpertName), v))
	})
}

// ExpertNameEqualFold applies the EqualFold predicate on the "expert_name" field.
func ExpertNameEqualFold(v string) predicate.Expert {
	return predicate.Expert(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldExpertName), v))
	})
}

// ExpertNameContainsFold applies the ContainsFold predicate on the "expert_name" field.
func ExpertNameContainsFold(v string) predicate.Expert {
	return predicate.Expert(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldExpertName), v))
	})
}

// HasDentists applies the HasEdge predicate on the "dentists" edge.
func HasDentists() predicate.Expert {
	return predicate.Expert(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DentistsTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DentistsTable, DentistsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDentistsWith applies the HasEdge predicate on the "dentists" edge with a given conditions (other predicates).
func HasDentistsWith(preds ...predicate.Dentist) predicate.Expert {
	return predicate.Expert(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DentistsInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DentistsTable, DentistsColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Expert) predicate.Expert {
	return predicate.Expert(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Expert) predicate.Expert {
	return predicate.Expert(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Expert) predicate.Expert {
	return predicate.Expert(func(s *sql.Selector) {
		p(s.Not())
	})
}
