// Code generated by entc, DO NOT EDIT.

package dentalexpense

const (
	// Label holds the string label denoting the dentalexpense type in the database.
	Label = "dentalexpense"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPhone holds the string denoting the phone field in the database.
	FieldPhone = "phone"
	// FieldAddedTime holds the string denoting the addedtime field in the database.
	FieldAddedTime = "added_time"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldTax holds the string denoting the tax field in the database.
	FieldTax = "tax"

	// EdgeNurse holds the string denoting the nurse edge name in mutations.
	EdgeNurse = "nurse"
	// EdgeMedicalfile holds the string denoting the medicalfile edge name in mutations.
	EdgeMedicalfile = "medicalfile"
	// EdgePricetype holds the string denoting the pricetype edge name in mutations.
	EdgePricetype = "pricetype"

	// Table holds the table name of the dentalexpense in the database.
	Table = "dentalexpenses"
	// NurseTable is the table the holds the nurse relation/edge.
	NurseTable = "dentalexpenses"
	// NurseInverseTable is the table name for the Nurse entity.
	// It exists in this package in order to avoid circular dependency with the "nurse" package.
	NurseInverseTable = "nurses"
	// NurseColumn is the table column denoting the nurse relation/edge.
	NurseColumn = "nurse_id"
	// MedicalfileTable is the table the holds the medicalfile relation/edge.
	MedicalfileTable = "dentalexpenses"
	// MedicalfileInverseTable is the table name for the Medicalfile entity.
	// It exists in this package in order to avoid circular dependency with the "medicalfile" package.
	MedicalfileInverseTable = "medicalfiles"
	// MedicalfileColumn is the table column denoting the medicalfile relation/edge.
	MedicalfileColumn = "medicalfile_id"
	// PricetypeTable is the table the holds the pricetype relation/edge.
	PricetypeTable = "dentalexpenses"
	// PricetypeInverseTable is the table name for the Pricetype entity.
	// It exists in this package in order to avoid circular dependency with the "pricetype" package.
	PricetypeInverseTable = "pricetypes"
	// PricetypeColumn is the table column denoting the pricetype relation/edge.
	PricetypeColumn = "pricetype_id"
)

// Columns holds all SQL columns for dentalexpense fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldPhone,
	FieldAddedTime,
	FieldAmount,
	FieldTax,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Dentalexpense type.
var ForeignKeys = []string{
	"medicalfile_id",
	"nurse_id",
	"pricetype_id",
}

var (
	// NameValidator is a validator for the "Name" field. It is called by the builders before save.
	NameValidator func(string) error
	// PhoneValidator is a validator for the "Phone" field. It is called by the builders before save.
	PhoneValidator func(string) error
	// AmountValidator is a validator for the "Amount" field. It is called by the builders before save.
	AmountValidator func(int) error
	// TaxValidator is a validator for the "Tax" field. It is called by the builders before save.
	TaxValidator func(string) error
)
