// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/team03/app/ent/medicalcare"
)

// MedicalCare is the model entity for the MedicalCare schema.
type MedicalCare struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MedicalCareQuery when eager-loading is set.
	Edges MedicalCareEdges `json:"edges"`
}

// MedicalCareEdges holds the relations/edges for other nodes in the graph.
type MedicalCareEdges struct {
	// Patients holds the value of the patients edge.
	Patients []*Patient
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PatientsOrErr returns the Patients value or an error if the edge
// was not loaded in eager-loading.
func (e MedicalCareEdges) PatientsOrErr() ([]*Patient, error) {
	if e.loadedTypes[0] {
		return e.Patients, nil
	}
	return nil, &NotLoadedError{edge: "patients"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MedicalCare) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // name
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MedicalCare fields.
func (mc *MedicalCare) assignValues(values ...interface{}) error {
	if m, n := len(values), len(medicalcare.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	mc.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field name", values[0])
	} else if value.Valid {
		mc.Name = value.String
	}
	return nil
}

// QueryPatients queries the patients edge of the MedicalCare.
func (mc *MedicalCare) QueryPatients() *PatientQuery {
	return (&MedicalCareClient{config: mc.config}).QueryPatients(mc)
}

// Update returns a builder for updating this MedicalCare.
// Note that, you need to call MedicalCare.Unwrap() before calling this method, if this MedicalCare
// was returned from a transaction, and the transaction was committed or rolled back.
func (mc *MedicalCare) Update() *MedicalCareUpdateOne {
	return (&MedicalCareClient{config: mc.config}).UpdateOne(mc)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (mc *MedicalCare) Unwrap() *MedicalCare {
	tx, ok := mc.config.driver.(*txDriver)
	if !ok {
		panic("ent: MedicalCare is not a transactional entity")
	}
	mc.config.driver = tx.drv
	return mc
}

// String implements the fmt.Stringer.
func (mc *MedicalCare) String() string {
	var builder strings.Builder
	builder.WriteString("MedicalCare(")
	builder.WriteString(fmt.Sprintf("id=%v", mc.ID))
	builder.WriteString(", name=")
	builder.WriteString(mc.Name)
	builder.WriteByte(')')
	return builder.String()
}

// MedicalCares is a parsable slice of MedicalCare.
type MedicalCares []*MedicalCare

func (mc MedicalCares) config(cfg config) {
	for _i := range mc {
		mc[_i].config = cfg
	}
}
