// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/team03/app/ent/appointment"
	"github.com/team03/app/ent/disease"
	"github.com/team03/app/ent/gender"
	"github.com/team03/app/ent/medicalcare"
	"github.com/team03/app/ent/medicalfile"
	"github.com/team03/app/ent/nurse"
	"github.com/team03/app/ent/patient"
	"github.com/team03/app/ent/queue"
)

// PatientCreate is the builder for creating a Patient entity.
type PatientCreate struct {
	config
	mutation *PatientMutation
	hooks    []Hook
}

// SetPatientID sets the PatientID field.
func (pc *PatientCreate) SetPatientID(s string) *PatientCreate {
	pc.mutation.SetPatientID(s)
	return pc
}

// SetName sets the Name field.
func (pc *PatientCreate) SetName(s string) *PatientCreate {
	pc.mutation.SetName(s)
	return pc
}

// SetCardID sets the CardID field.
func (pc *PatientCreate) SetCardID(s string) *PatientCreate {
	pc.mutation.SetCardID(s)
	return pc
}

// SetTel sets the Tel field.
func (pc *PatientCreate) SetTel(s string) *PatientCreate {
	pc.mutation.SetTel(s)
	return pc
}

// SetAge sets the Age field.
func (pc *PatientCreate) SetAge(i int) *PatientCreate {
	pc.mutation.SetAge(i)
	return pc
}

// SetBirthday sets the Birthday field.
func (pc *PatientCreate) SetBirthday(t time.Time) *PatientCreate {
	pc.mutation.SetBirthday(t)
	return pc
}

// SetGenderID sets the gender edge to Gender by id.
func (pc *PatientCreate) SetGenderID(id int) *PatientCreate {
	pc.mutation.SetGenderID(id)
	return pc
}

// SetNillableGenderID sets the gender edge to Gender by id if the given value is not nil.
func (pc *PatientCreate) SetNillableGenderID(id *int) *PatientCreate {
	if id != nil {
		pc = pc.SetGenderID(*id)
	}
	return pc
}

// SetGender sets the gender edge to Gender.
func (pc *PatientCreate) SetGender(g *Gender) *PatientCreate {
	return pc.SetGenderID(g.ID)
}

// SetMedicalcareID sets the medicalcare edge to MedicalCare by id.
func (pc *PatientCreate) SetMedicalcareID(id int) *PatientCreate {
	pc.mutation.SetMedicalcareID(id)
	return pc
}

// SetNillableMedicalcareID sets the medicalcare edge to MedicalCare by id if the given value is not nil.
func (pc *PatientCreate) SetNillableMedicalcareID(id *int) *PatientCreate {
	if id != nil {
		pc = pc.SetMedicalcareID(*id)
	}
	return pc
}

// SetMedicalcare sets the medicalcare edge to MedicalCare.
func (pc *PatientCreate) SetMedicalcare(m *MedicalCare) *PatientCreate {
	return pc.SetMedicalcareID(m.ID)
}

// SetNurseID sets the nurse edge to Nurse by id.
func (pc *PatientCreate) SetNurseID(id int) *PatientCreate {
	pc.mutation.SetNurseID(id)
	return pc
}

// SetNillableNurseID sets the nurse edge to Nurse by id if the given value is not nil.
func (pc *PatientCreate) SetNillableNurseID(id *int) *PatientCreate {
	if id != nil {
		pc = pc.SetNurseID(*id)
	}
	return pc
}

// SetNurse sets the nurse edge to Nurse.
func (pc *PatientCreate) SetNurse(n *Nurse) *PatientCreate {
	return pc.SetNurseID(n.ID)
}

// SetDiseaseID sets the disease edge to Disease by id.
func (pc *PatientCreate) SetDiseaseID(id int) *PatientCreate {
	pc.mutation.SetDiseaseID(id)
	return pc
}

// SetNillableDiseaseID sets the disease edge to Disease by id if the given value is not nil.
func (pc *PatientCreate) SetNillableDiseaseID(id *int) *PatientCreate {
	if id != nil {
		pc = pc.SetDiseaseID(*id)
	}
	return pc
}

// SetDisease sets the disease edge to Disease.
func (pc *PatientCreate) SetDisease(d *Disease) *PatientCreate {
	return pc.SetDiseaseID(d.ID)
}

// AddMedicalfileIDs adds the medicalfiles edge to Medicalfile by ids.
func (pc *PatientCreate) AddMedicalfileIDs(ids ...int) *PatientCreate {
	pc.mutation.AddMedicalfileIDs(ids...)
	return pc
}

// AddMedicalfiles adds the medicalfiles edges to Medicalfile.
func (pc *PatientCreate) AddMedicalfiles(m ...*Medicalfile) *PatientCreate {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return pc.AddMedicalfileIDs(ids...)
}

// AddQueueIDs adds the queue edge to Queue by ids.
func (pc *PatientCreate) AddQueueIDs(ids ...int) *PatientCreate {
	pc.mutation.AddQueueIDs(ids...)
	return pc
}

// AddQueue adds the queue edges to Queue.
func (pc *PatientCreate) AddQueue(q ...*Queue) *PatientCreate {
	ids := make([]int, len(q))
	for i := range q {
		ids[i] = q[i].ID
	}
	return pc.AddQueueIDs(ids...)
}

// AddAppointmentIDs adds the appointment edge to Appointment by ids.
func (pc *PatientCreate) AddAppointmentIDs(ids ...int) *PatientCreate {
	pc.mutation.AddAppointmentIDs(ids...)
	return pc
}

// AddAppointment adds the appointment edges to Appointment.
func (pc *PatientCreate) AddAppointment(a ...*Appointment) *PatientCreate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return pc.AddAppointmentIDs(ids...)
}

// Mutation returns the PatientMutation object of the builder.
func (pc *PatientCreate) Mutation() *PatientMutation {
	return pc.mutation
}

// Save creates the Patient in the database.
func (pc *PatientCreate) Save(ctx context.Context) (*Patient, error) {
	if _, ok := pc.mutation.PatientID(); !ok {
		return nil, &ValidationError{Name: "PatientID", err: errors.New("ent: missing required field \"PatientID\"")}
	}
	if v, ok := pc.mutation.PatientID(); ok {
		if err := patient.PatientIDValidator(v); err != nil {
			return nil, &ValidationError{Name: "PatientID", err: fmt.Errorf("ent: validator failed for field \"PatientID\": %w", err)}
		}
	}
	if _, ok := pc.mutation.Name(); !ok {
		return nil, &ValidationError{Name: "Name", err: errors.New("ent: missing required field \"Name\"")}
	}
	if v, ok := pc.mutation.Name(); ok {
		if err := patient.NameValidator(v); err != nil {
			return nil, &ValidationError{Name: "Name", err: fmt.Errorf("ent: validator failed for field \"Name\": %w", err)}
		}
	}
	if _, ok := pc.mutation.CardID(); !ok {
		return nil, &ValidationError{Name: "CardID", err: errors.New("ent: missing required field \"CardID\"")}
	}
	if v, ok := pc.mutation.CardID(); ok {
		if err := patient.CardIDValidator(v); err != nil {
			return nil, &ValidationError{Name: "CardID", err: fmt.Errorf("ent: validator failed for field \"CardID\": %w", err)}
		}
	}
	if _, ok := pc.mutation.Tel(); !ok {
		return nil, &ValidationError{Name: "Tel", err: errors.New("ent: missing required field \"Tel\"")}
	}
	if v, ok := pc.mutation.Tel(); ok {
		if err := patient.TelValidator(v); err != nil {
			return nil, &ValidationError{Name: "Tel", err: fmt.Errorf("ent: validator failed for field \"Tel\": %w", err)}
		}
	}
	if _, ok := pc.mutation.Age(); !ok {
		return nil, &ValidationError{Name: "Age", err: errors.New("ent: missing required field \"Age\"")}
	}
	if v, ok := pc.mutation.Age(); ok {
		if err := patient.AgeValidator(v); err != nil {
			return nil, &ValidationError{Name: "Age", err: fmt.Errorf("ent: validator failed for field \"Age\": %w", err)}
		}
	}
	if _, ok := pc.mutation.Birthday(); !ok {
		return nil, &ValidationError{Name: "Birthday", err: errors.New("ent: missing required field \"Birthday\"")}
	}
	var (
		err  error
		node *Patient
	)
	if len(pc.hooks) == 0 {
		node, err = pc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PatientMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pc.mutation = mutation
			node, err = pc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(pc.hooks) - 1; i >= 0; i-- {
			mut = pc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PatientCreate) SaveX(ctx context.Context) *Patient {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pc *PatientCreate) sqlSave(ctx context.Context) (*Patient, error) {
	pa, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	pa.ID = int(id)
	return pa, nil
}

func (pc *PatientCreate) createSpec() (*Patient, *sqlgraph.CreateSpec) {
	var (
		pa    = &Patient{config: pc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: patient.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: patient.FieldID,
			},
		}
	)
	if value, ok := pc.mutation.PatientID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: patient.FieldPatientID,
		})
		pa.PatientID = value
	}
	if value, ok := pc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: patient.FieldName,
		})
		pa.Name = value
	}
	if value, ok := pc.mutation.CardID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: patient.FieldCardID,
		})
		pa.CardID = value
	}
	if value, ok := pc.mutation.Tel(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: patient.FieldTel,
		})
		pa.Tel = value
	}
	if value, ok := pc.mutation.Age(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: patient.FieldAge,
		})
		pa.Age = value
	}
	if value, ok := pc.mutation.Birthday(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: patient.FieldBirthday,
		})
		pa.Birthday = value
	}
	if nodes := pc.mutation.GenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   patient.GenderTable,
			Columns: []string{patient.GenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: gender.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pc.mutation.MedicalcareIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   patient.MedicalcareTable,
			Columns: []string{patient.MedicalcareColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: medicalcare.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pc.mutation.NurseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   patient.NurseTable,
			Columns: []string{patient.NurseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: nurse.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pc.mutation.DiseaseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   patient.DiseaseTable,
			Columns: []string{patient.DiseaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: disease.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pc.mutation.MedicalfilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   patient.MedicalfilesTable,
			Columns: []string{patient.MedicalfilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: medicalfile.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pc.mutation.QueueIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   patient.QueueTable,
			Columns: []string{patient.QueueColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: queue.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pc.mutation.AppointmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   patient.AppointmentTable,
			Columns: []string{patient.AppointmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: appointment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return pa, _spec
}
