// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/team03/app/ent/dentalexpense"
	"github.com/team03/app/ent/pricetype"
)

// PricetypeCreate is the builder for creating a Pricetype entity.
type PricetypeCreate struct {
	config
	mutation *PricetypeMutation
	hooks    []Hook
}

// SetName sets the name field.
func (pc *PricetypeCreate) SetName(s string) *PricetypeCreate {
	pc.mutation.SetName(s)
	return pc
}

// AddDentalexpenseIDs adds the dentalexpenses edge to Dentalexpense by ids.
func (pc *PricetypeCreate) AddDentalexpenseIDs(ids ...int) *PricetypeCreate {
	pc.mutation.AddDentalexpenseIDs(ids...)
	return pc
}

// AddDentalexpenses adds the dentalexpenses edges to Dentalexpense.
func (pc *PricetypeCreate) AddDentalexpenses(d ...*Dentalexpense) *PricetypeCreate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return pc.AddDentalexpenseIDs(ids...)
}

// Mutation returns the PricetypeMutation object of the builder.
func (pc *PricetypeCreate) Mutation() *PricetypeMutation {
	return pc.mutation
}

// Save creates the Pricetype in the database.
func (pc *PricetypeCreate) Save(ctx context.Context) (*Pricetype, error) {
	if _, ok := pc.mutation.Name(); !ok {
		return nil, &ValidationError{Name: "name", err: errors.New("ent: missing required field \"name\"")}
	}
	var (
		err  error
		node *Pricetype
	)
	if len(pc.hooks) == 0 {
		node, err = pc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PricetypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pc.mutation = mutation
			node, err = pc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(pc.hooks) - 1; i >= 0; i-- {
			mut = pc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PricetypeCreate) SaveX(ctx context.Context) *Pricetype {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pc *PricetypeCreate) sqlSave(ctx context.Context) (*Pricetype, error) {
	pr, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	pr.ID = int(id)
	return pr, nil
}

func (pc *PricetypeCreate) createSpec() (*Pricetype, *sqlgraph.CreateSpec) {
	var (
		pr    = &Pricetype{config: pc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: pricetype.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: pricetype.FieldID,
			},
		}
	)
	if value, ok := pc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: pricetype.FieldName,
		})
		pr.Name = value
	}
	if nodes := pc.mutation.DentalexpensesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pricetype.DentalexpensesTable,
			Columns: []string{pricetype.DentalexpensesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: dentalexpense.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return pr, _spec
}
