// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/team03/app/ent/dentalexpense"
	"github.com/team03/app/ent/predicate"
	"github.com/team03/app/ent/pricetype"
)

// PricetypeUpdate is the builder for updating Pricetype entities.
type PricetypeUpdate struct {
	config
	hooks      []Hook
	mutation   *PricetypeMutation
	predicates []predicate.Pricetype
}

// Where adds a new predicate for the builder.
func (pu *PricetypeUpdate) Where(ps ...predicate.Pricetype) *PricetypeUpdate {
	pu.predicates = append(pu.predicates, ps...)
	return pu
}

// SetName sets the name field.
func (pu *PricetypeUpdate) SetName(s string) *PricetypeUpdate {
	pu.mutation.SetName(s)
	return pu
}

// AddDentalexpenseIDs adds the dentalexpenses edge to Dentalexpense by ids.
func (pu *PricetypeUpdate) AddDentalexpenseIDs(ids ...int) *PricetypeUpdate {
	pu.mutation.AddDentalexpenseIDs(ids...)
	return pu
}

// AddDentalexpenses adds the dentalexpenses edges to Dentalexpense.
func (pu *PricetypeUpdate) AddDentalexpenses(d ...*Dentalexpense) *PricetypeUpdate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return pu.AddDentalexpenseIDs(ids...)
}

// Mutation returns the PricetypeMutation object of the builder.
func (pu *PricetypeUpdate) Mutation() *PricetypeMutation {
	return pu.mutation
}

// RemoveDentalexpenseIDs removes the dentalexpenses edge to Dentalexpense by ids.
func (pu *PricetypeUpdate) RemoveDentalexpenseIDs(ids ...int) *PricetypeUpdate {
	pu.mutation.RemoveDentalexpenseIDs(ids...)
	return pu
}

// RemoveDentalexpenses removes dentalexpenses edges to Dentalexpense.
func (pu *PricetypeUpdate) RemoveDentalexpenses(d ...*Dentalexpense) *PricetypeUpdate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return pu.RemoveDentalexpenseIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (pu *PricetypeUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(pu.hooks) == 0 {
		affected, err = pu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PricetypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pu.mutation = mutation
			affected, err = pu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pu.hooks) - 1; i >= 0; i-- {
			mut = pu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (pu *PricetypeUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *PricetypeUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *PricetypeUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pu *PricetypeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   pricetype.Table,
			Columns: pricetype.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: pricetype.FieldID,
			},
		},
	}
	if ps := pu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: pricetype.FieldName,
		})
	}
	if nodes := pu.mutation.RemovedDentalexpensesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pricetype.DentalexpensesTable,
			Columns: []string{pricetype.DentalexpensesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: dentalexpense.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.DentalexpensesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pricetype.DentalexpensesTable,
			Columns: []string{pricetype.DentalexpensesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: dentalexpense.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pricetype.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// PricetypeUpdateOne is the builder for updating a single Pricetype entity.
type PricetypeUpdateOne struct {
	config
	hooks    []Hook
	mutation *PricetypeMutation
}

// SetName sets the name field.
func (puo *PricetypeUpdateOne) SetName(s string) *PricetypeUpdateOne {
	puo.mutation.SetName(s)
	return puo
}

// AddDentalexpenseIDs adds the dentalexpenses edge to Dentalexpense by ids.
func (puo *PricetypeUpdateOne) AddDentalexpenseIDs(ids ...int) *PricetypeUpdateOne {
	puo.mutation.AddDentalexpenseIDs(ids...)
	return puo
}

// AddDentalexpenses adds the dentalexpenses edges to Dentalexpense.
func (puo *PricetypeUpdateOne) AddDentalexpenses(d ...*Dentalexpense) *PricetypeUpdateOne {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return puo.AddDentalexpenseIDs(ids...)
}

// Mutation returns the PricetypeMutation object of the builder.
func (puo *PricetypeUpdateOne) Mutation() *PricetypeMutation {
	return puo.mutation
}

// RemoveDentalexpenseIDs removes the dentalexpenses edge to Dentalexpense by ids.
func (puo *PricetypeUpdateOne) RemoveDentalexpenseIDs(ids ...int) *PricetypeUpdateOne {
	puo.mutation.RemoveDentalexpenseIDs(ids...)
	return puo
}

// RemoveDentalexpenses removes dentalexpenses edges to Dentalexpense.
func (puo *PricetypeUpdateOne) RemoveDentalexpenses(d ...*Dentalexpense) *PricetypeUpdateOne {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return puo.RemoveDentalexpenseIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (puo *PricetypeUpdateOne) Save(ctx context.Context) (*Pricetype, error) {

	var (
		err  error
		node *Pricetype
	)
	if len(puo.hooks) == 0 {
		node, err = puo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PricetypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			puo.mutation = mutation
			node, err = puo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(puo.hooks) - 1; i >= 0; i-- {
			mut = puo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, puo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (puo *PricetypeUpdateOne) SaveX(ctx context.Context) *Pricetype {
	pr, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return pr
}

// Exec executes the query on the entity.
func (puo *PricetypeUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *PricetypeUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (puo *PricetypeUpdateOne) sqlSave(ctx context.Context) (pr *Pricetype, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   pricetype.Table,
			Columns: pricetype.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: pricetype.FieldID,
			},
		},
	}
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Pricetype.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := puo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: pricetype.FieldName,
		})
	}
	if nodes := puo.mutation.RemovedDentalexpensesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pricetype.DentalexpensesTable,
			Columns: []string{pricetype.DentalexpensesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: dentalexpense.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.DentalexpensesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pricetype.DentalexpensesTable,
			Columns: []string{pricetype.DentalexpensesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: dentalexpense.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	pr = &Pricetype{config: puo.config}
	_spec.Assign = pr.assignValues
	_spec.ScanValues = pr.scanValues()
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pricetype.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return pr, nil
}
