// Code generated by entc, DO NOT EDIT.

package queue

const (
	// Label holds the string label denoting the queue type in the database.
	Label = "queue"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDental holds the string denoting the dental field in the database.
	FieldDental = "dental"
	// FieldQueueTime holds the string denoting the queue_time field in the database.
	FieldQueueTime = "queue_time"

	// EdgeDentist holds the string denoting the dentist edge name in mutations.
	EdgeDentist = "dentist"
	// EdgeNurse holds the string denoting the nurse edge name in mutations.
	EdgeNurse = "nurse"
	// EdgePatient holds the string denoting the patient edge name in mutations.
	EdgePatient = "patient"

	// Table holds the table name of the queue in the database.
	Table = "queues"
	// DentistTable is the table the holds the dentist relation/edge.
	DentistTable = "queues"
	// DentistInverseTable is the table name for the Dentist entity.
	// It exists in this package in order to avoid circular dependency with the "dentist" package.
	DentistInverseTable = "dentists"
	// DentistColumn is the table column denoting the dentist relation/edge.
	DentistColumn = "dentist_id"
	// NurseTable is the table the holds the nurse relation/edge.
	NurseTable = "queues"
	// NurseInverseTable is the table name for the Nurse entity.
	// It exists in this package in order to avoid circular dependency with the "nurse" package.
	NurseInverseTable = "nurses"
	// NurseColumn is the table column denoting the nurse relation/edge.
	NurseColumn = "nurse_id"
	// PatientTable is the table the holds the patient relation/edge.
	PatientTable = "queues"
	// PatientInverseTable is the table name for the Patient entity.
	// It exists in this package in order to avoid circular dependency with the "patient" package.
	PatientInverseTable = "patients"
	// PatientColumn is the table column denoting the patient relation/edge.
	PatientColumn = "patient_id"
)

// Columns holds all SQL columns for queue fields.
var Columns = []string{
	FieldID,
	FieldDental,
	FieldQueueTime,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Queue type.
var ForeignKeys = []string{
	"dentist_id",
	"nurse_id",
	"patient_id",
}
