/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntMedicalfile,
    EntMedicalfileFromJSON,
    EntMedicalfileFromJSONTyped,
    EntMedicalfileToJSON,
    EntNurse,
    EntNurseFromJSON,
    EntNurseFromJSONTyped,
    EntNurseToJSON,
    EntPricetype,
    EntPricetypeFromJSON,
    EntPricetypeFromJSONTyped,
    EntPricetypeToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntDentalexpenseEdges
 */
export interface EntDentalexpenseEdges {
    /**
     * 
     * @type {EntMedicalfile}
     * @memberof EntDentalexpenseEdges
     */
    medicalfile?: EntMedicalfile;
    /**
     * 
     * @type {EntNurse}
     * @memberof EntDentalexpenseEdges
     */
    nurse?: EntNurse;
    /**
     * 
     * @type {EntPricetype}
     * @memberof EntDentalexpenseEdges
     */
    pricetype?: EntPricetype;
}

export function EntDentalexpenseEdgesFromJSON(json: any): EntDentalexpenseEdges {
    return EntDentalexpenseEdgesFromJSONTyped(json, false);
}

export function EntDentalexpenseEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntDentalexpenseEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'medicalfile': !exists(json, 'Medicalfile') ? undefined : EntMedicalfileFromJSON(json['Medicalfile']),
        'nurse': !exists(json, 'Nurse') ? undefined : EntNurseFromJSON(json['Nurse']),
        'pricetype': !exists(json, 'Pricetype') ? undefined : EntPricetypeFromJSON(json['Pricetype']),
    };
}

export function EntDentalexpenseEdgesToJSON(value?: EntDentalexpenseEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'medicalfile': EntMedicalfileToJSON(value.medicalfile),
        'nurse': EntNurseToJSON(value.nurse),
        'pricetype': EntPricetypeToJSON(value.pricetype),
    };
}


