/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntExpertEdges,
    EntExpertEdgesFromJSON,
    EntExpertEdgesFromJSONTyped,
    EntExpertEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntExpert
 */
export interface EntExpert {
    /**
     * 
     * @type {EntExpertEdges}
     * @memberof EntExpert
     */
    edges?: EntExpertEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntExpert
     */
    id?: number;
    /**
     * Name holds the value of the "name" field.
     * @type {string}
     * @memberof EntExpert
     */
    name?: string;
}

export function EntExpertFromJSON(json: any): EntExpert {
    return EntExpertFromJSONTyped(json, false);
}

export function EntExpertFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntExpert {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'edges': !exists(json, 'edges') ? undefined : EntExpertEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function EntExpertToJSON(value?: EntExpert | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'edges': EntExpertEdgesToJSON(value.edges),
        'id': value.id,
        'name': value.name,
    };
}


